# Generated by Django 5.1.5 on 2025-03-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Telegram User ID"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Joined"),
                ),
                (
                    "last_active",
                    models.DateTimeField(auto_now=True, verbose_name="Last Active"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Is Admin"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Telegram User",
                "verbose_name_plural": "Telegram Users",
                "ordering": ["-last_active"],
            },
        ),
    ]
