# Generated by Django 5.1.5 on 2025-03-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("channel", "Kanal"), ("group", "Guruh")],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyFunFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Fun fact text")),
                ("options", models.JSONField(verbose_name="Fun fact options")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamousQuotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField(verbose_name="Famous quote text")),
                (
                    "author",
                    models.CharField(
                        max_length=255, verbose_name="Famous quote author"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuotesForBio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=255, verbose_name="Quotes author"),
                ),
                ("quote", models.TextField(verbose_name="Quote text")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="best_streak",
            field=models.IntegerField(
                default=0, verbose_name="Eng yaxshi ketma-ketlik"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="correct_answers",
            field=models.IntegerField(default=0, verbose_name="To'g'ri javoblar soni"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="current_streak",
            field=models.IntegerField(default=0, verbose_name="Joriy ketma-ketlik"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="highest_score",
            field=models.IntegerField(default=0, verbose_name="Eng yuqori natija"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="last_quiz_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Oxirgi o'yin sanasi"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="participated_quizzes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="total_points",
            field=models.IntegerField(default=0, verbose_name="Jami to'plangan ballar"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="total_questions_answered",
            field=models.IntegerField(
                default=0, verbose_name="Jami javob berilgan savollar"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="wrong_answers",
            field=models.IntegerField(
                default=0, verbose_name="Noto'g'ri javoblar soni"
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("full_name", models.CharField(max_length=255)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Bot.channel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                        verbose_name="Difficulty Level",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("multiple", "Multiple Choice"),
                            ("boolean", "True/False"),
                        ],
                        default="multiple",
                        max_length=10,
                        verbose_name="Question Type",
                    ),
                ),
                (
                    "incorrect_answers",
                    models.JSONField(
                        help_text="Multiple choice uchun variantlar ro'yxati, boolean uchun bo'sh massiv",
                        verbose_name="Incorrect Answers",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Multiple choice uchun to'g'ri javob, boolean uchun 'True' yoki 'False'",
                        max_length=255,
                        verbose_name="Correct Answer",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bot.quizcategory",
                        verbose_name="Quiz Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Taklif qilingan sana"
                    ),
                ),
                (
                    "referral_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Referral narxi",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="Bot.telegramuser",
                        verbose_name="Taklif qilingan foydalanuvchi",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_users",
                        to="Bot.telegramuser",
                        verbose_name="Taklif qiluvchi foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referral",
            },
        ),
    ]
