# Generated by Django 5.1.5 on 2025-03-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0002_channel_dailyfunfact_famousquotes_quizcategory_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyFunFact",
        ),
        migrations.DeleteModel(
            name="FamousQuotes",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="category",
        ),
        migrations.DeleteModel(
            name="QuotesForBio",
        ),
        migrations.DeleteModel(
            name="QuizCategory",
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
    ]
