# Generated by Django 5.1.5 on 2025-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0003_delete_dailyfunfact_delete_famousquotes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="type",
            field=models.CharField(
                choices=[
                    ("channel", "Kanal"),
                    ("group", "Guruh"),
                    ("joinrequest", "JoinRequest"),
                ],
                max_length=15,
            ),
        ),
    ]
