# Generated by Django 5.1.5 on 2025-06-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0004_alter_channel_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JoinRequest",
        ),
    ]
