# Generated by Django 5.1.5 on 2025-06-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0005_delete_joinrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Sarlavha")),
                ("content", models.TextField(verbose_name="Kontent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
            },
        ),
    ]
