# Generated by Django 5.1.5 on 2025-06-13 02:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0006_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
