# Generated by Django 5.1.5 on 2025-06-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0008_alter_guide_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="content",
            field=models.TextField(verbose_name="Kontent"),
        ),
    ]
