# Generated by Django 5.1.5 on 2025-06-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0009_alter_guide_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Holat"),
        ),
    ]
