# Generated by Django 5.1.5 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0011_appeal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramuser",
            name="best_streak",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="correct_answers",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="highest_score",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="last_quiz_date",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="participated_quizzes_count",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="total_points",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="total_questions_answered",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="wrong_answers",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="access_token",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Access Token"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="refresh_token",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Refresh Token"
            ),
        ),
    ]
